#!/usr/bin/env python3
"""Refresh local distillation assets without overwriting curated knowledge."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path


def load_json(path: Path, default=None):
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def resolve(project: Path, path: Path) -> Path:
    return path if path.is_absolute() else project / path


def run(script_dir: Path, script: str, *args: str) -> None:
    subprocess.run([sys.executable, str(script_dir / script), *map(str, args)], check=True)


def parse_lineage_bibcodes(path: Path) -> list[str]:
    return sorted(set(re.findall(r"`(\d{4}[^`]+)`", path.read_text(encoding="utf-8"))))


def render_queue(path: Path, queue: dict) -> None:
    lines = [
        "# Manual Review Queue",
        "",
        "This report is generated by the conservative refresh command. Curated JSON is never overwritten automatically.",
        "",
        "## Preflight",
        "",
        "- ADS collection and public-PDF download remain explicit preflight steps because identity and evidence promotion require review.",
        "- Use `--include-method-graph` only when a network-backed OpenAlex refresh is intended.",
        "",
    ]
    for key, label in [
        ("added_manifest_bibcodes", "New manifest records"),
        ("removed_manifest_bibcodes", "Removed manifest records"),
        ("lineage_without_deep_card", "Lineage papers without deep cards"),
        ("deep_cards_outside_manifest", "Deep cards outside the formal manifest"),
        ("citation_contexts_without_hits", "Citation contexts without full-text hits"),
        ("citation_contexts_needing_user_review", "Citation contexts needing user review"),
    ]:
        lines.extend([f"## {label}", ""])
        values = queue[key]
        lines.extend(f"- `{value}`" for value in values)
        if not values:
            lines.append("- None.")
        lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-dir", type=Path, default=Path("."))
    parser.add_argument("--lineage", type=Path, required=True)
    parser.add_argument("--skill-dir", type=Path, required=True)
    parser.add_argument("--skip-base-assets", action="store_true")
    parser.add_argument("--include-method-graph", action="store_true")
    args = parser.parse_args()

    project = args.project_dir.resolve()
    lineage = resolve(project, args.lineage)
    skill_dir = resolve(project, args.skill_dir)
    references = skill_dir / "references"
    script_dir = Path(__file__).resolve().parent

    if not args.skip_base_assets:
        run(
            script_dir,
            "generate_research_assets.py",
            "--config", project / "config/astronomer.json",
            "--manifest", project / "metadata/paper_manifest.json",
            "--verification", project / "metadata/correspondence_audit_verification.json",
            "--openalex-works", project / "metadata/openalex_works.json",
            "--lineage", lineage,
            "--text-dir", project / "text",
            "--cards-json", project / "distillation/paper-cards.json",
            "--cards-md", project / "distillation/paper-cards.md",
            "--ledger", project / "metadata/evidence-ledger.jsonl",
            "--graph-json", project / "metadata/research-graph.json",
            "--snapshot", project / "metadata/distillation-snapshot.json",
            "--update-report", project / "metadata/update-report.json",
            "--profile-md", references / "researcher-profile.md",
            "--graph-md", references / "collaboration-map.md",
            "--holdout-md", references / "holdout-evaluation.md",
        )

    run(
        script_dir,
        "generate_rolling_holdout.py",
        "--config", project / "config/astronomer.json",
        "--manifest", project / "metadata/paper_manifest.json",
        "--output", references / "rolling-holdout-evaluation.md",
    )
    if args.include_method_graph:
        run(
            script_dir,
            "build_method_graph.py",
            "--config", project / "config/astronomer.json",
            "--manifest", project / "metadata/paper_manifest.json",
            "--lineage", lineage,
            "--openalex-works", project / "metadata/openalex_works.json",
            "--output", project / "metadata/method-graph.json",
            "--comparison-output", project / "metadata/external-comparison-candidates.json",
            "--markdown-output", references / "method-graph.md",
        )

    curated = [
        ("render_deep_cards.py", "deep-paper-cards.json", "deep-paper-cards.md", "--cards"),
        ("render_method_boundaries.py", "method-boundaries.json", "method-boundaries.md", "--boundaries"),
        ("render_version_relations.py", "version-relations.json", "version-relations.md", "--relations"),
        ("render_claim_ledger.py", "atomic-claims.json", "atomic-claim-ledger.md", "--ledger"),
    ]
    for script, source, output, flag in curated:
        source_path = project / "distillation" / source
        if source_path.exists():
            run(script_dir, script, flag, source_path, "--output", references / output)

    seed_path = project / "distillation/core-citation-context-seeds.json"
    context_path = project / "metadata/core-citation-contexts.json"
    if seed_path.exists():
        run(
            script_dir,
            "extract_citation_contexts.py",
            "--seeds", seed_path,
            "--text-dir", project / "text",
            "--output-json", context_path,
            "--output-md", references / "core-citation-contexts.md",
        )

    run(
        script_dir,
        "validate_lineage_refs.py",
        "--manifest", project / "metadata/paper_manifest.json",
        "--lineage", lineage,
    )

    manifest = load_json(project / "metadata/paper_manifest.json", []) or []
    update = load_json(project / "metadata/update-report.json", {}) or {}
    deep_cards = load_json(project / "distillation/deep-paper-cards.json", []) or []
    contexts = load_json(context_path, []) or []
    manifest_bibcodes = {item["bibcode"] for item in manifest}
    lineage_bibcodes = set(parse_lineage_bibcodes(lineage))
    deep_bibcodes = {item["bibcode"] for item in deep_cards}
    queue = {
        "added_manifest_bibcodes": update.get("added_bibcodes", []),
        "removed_manifest_bibcodes": update.get("removed_bibcodes", []),
        "lineage_without_deep_card": sorted(lineage_bibcodes - deep_bibcodes),
        "deep_cards_outside_manifest": sorted(deep_bibcodes - manifest_bibcodes),
        "citation_contexts_without_hits": sorted(
            f"{item['source_bibcode']}->{item['target_bibcode']}"
            for item in contexts
            if not item.get("hit_count")
        ),
        "citation_contexts_needing_user_review": sorted(
            f"{item['source_bibcode']}->{item['target_bibcode']}"
            for item in contexts
            if item.get("needs_user_review")
        ),
    }
    write_json(project / "metadata/manual-review-queue.json", queue)
    render_queue(references / "manual-review-queue.md", queue)
    print(json.dumps(queue, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
